### ISSUE TITLE
[BUG] VS Code command window sluggish after terminate

### ISSUE THREAD

**Issue by mattnieland** [DopplerHQ/cli#324]
**Describe the bug**
When terminating a session in VS Code that's been called with doppler run, the terminal window is sluggish and unresponsive.  Have to close it and re-open a new terminal.  Is there a reason/fix for this?

**To Reproduce**
Steps to reproduce the behavior. Please include output from running the command with `--debug`.
[Windows User]
Open VS Code.
Launch your app with doppler run... Example:  doppler run --command="start-server"
Terminate the app.
Try to type in the Terminal window of VS Code.  Doesn't work too well.  Have to hit the delete button and Ctrl + ` to re-open a new window.

**Comment by ryan-blunden** [comment]
Hi @mattnieland!

Just to clarify, is the processing terminating immediately but there is a delay between when you can then type in the terminal? A screen recording if possible would be great.

So I can best determine what the issue is, could you provide some additional information:

* Windows version
* Integrated shell
* Language and framework are you using
* Is the Doppler CLI running a command or executing a script?

**Comment by Piccirello** [comment]
Closing due to lack of response.
